const mongoose = require('mongoose');

/**
 * Chunk Schema for Vector RAG & Adaptive Semantic Passages.
 * Stores page-bounded passages and 768-dimensional vector embeddings
 * generated by Google gemini-embedding-001.
 *
 * Research Principles:
 * - LegRAG: Page-boundary invariance (chunks never cross page transitions).
 * - Matryoshka Representation Learning: 768-dimensional compact vectors.
 */
const chunkSchema = new mongoose.Schema({
  fileId: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'File',
    required: true,
    index: true,
  },
  uploadedBy: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'User',
    required: true,
    index: true,
  },
  pageNumber: {
    type: Number,
    required: true,
    min: 1,
  },
  chunkIndex: {
    type: Number,
    required: true,
    min: 0,
  },
  text: {
    type: String,
    required: true,
    trim: true,
  },
  charLength: {
    type: Number,
    required: true,
    min: 0,
  },
  embedding: {
    type: [Number],
    required: true,
    validate: {
      validator: function (val) {
        return Array.isArray(val) && val.length > 0;
      },
      message: 'Embedding must be a non-empty array of numerical coordinates.',
    },
  },
  createdAt: {
    type: Date,
    default: Date.now,
  },
});

// Compound indexes for user-isolated queries and ordered retrieval
chunkSchema.index({ uploadedBy: 1, fileId: 1, pageNumber: 1 });
chunkSchema.index({ fileId: 1, chunkIndex: 1 });

module.exports = mongoose.model('Chunk', chunkSchema);
